services:
  db:
    image: postgres:17-alpine
    env_file: .env
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  